/**
 * Scrim
 *
 * A soft gradient wash that keeps type legible over photography, with no
 * gradient dependency.
 *
 * It stretches an 8x512 PNG whose alpha ramps from 0 to 1 along an ease-in
 * curve, tinted to the theme's scrim colour. The obvious alternative — stacking
 * translucent bands — produces visible banding on smooth, low-contrast areas
 * such as a pale sky, because every band boundary is a hard edge. Letting the
 * GPU interpolate a real image avoids that entirely, and costs one node instead
 * of twenty.
 *
 * The asset is generated by `scripts/generate-scrim.py`.
 */

import { Image, StyleSheet } from 'react-native';
import type { ImageStyle, StyleProp } from 'react-native';

const SCRIM_SOURCE = require('../assets/scrim.png');

interface ScrimProps {
  /** Which edge the scrim is darkest at. */
  anchor?: 'top' | 'bottom';
  /** Scrim colour — normally `theme.color.scrim`. */
  color: string;
  /** Peak opacity at the anchored edge, 0–1. */
  intensity?: number;
  /**
   * Positioning override, e.g. `{ top: '38%' }` to keep the upper part of the
   * photograph completely clean.
   */
  style?: StyleProp<ImageStyle>;
}

export function Scrim({
  anchor = 'bottom',
  color,
  intensity = 0.92,
  style,
}: ScrimProps) {
  return (
    <Image
      source={SCRIM_SOURCE}
      resizeMode="stretch"
      tintColor={color}
      style={[
        StyleSheet.absoluteFill,
        { opacity: intensity },
        anchor === 'top' ? styles.flipped : null,
        style,
      ]}
    />
  );
}

const styles = StyleSheet.create({
  flipped: {
    transform: [{ scaleY: -1 }],
  },
});

export default Scrim;
